import type { InitialAPI } from '@midnight-ntwrk/dapp-connector-api';
import { useCallback, useEffect, useState } from 'react';
import { friendlyError } from './errors';
import { DEFAULT_CONTRACT_ADDRESS } from './midnight/config';
import { NightBidMarket, type PublicMarketState } from './midnight/nightbid-api';
import {
  connectWallet,
  describeInjectedWallets,
  detectWallets,
  type WalletSession,
} from './midnight/providers';

export type WalletFunds = {
  /** Address to paste into the Preprod faucet (tNIGHT is unshielded). */
  unshieldedAddress: string;
  /** Fee resource generated by held NIGHT. */
  dust: bigint;
  /** Sum of unshielded token balances (tNIGHT on Preprod). */
  night: bigint;
};

export type TxStatus =
  | { kind: 'idle' }
  | { kind: 'pending'; label: string }
  | { kind: 'success'; label: string; txId: string }
  | { kind: 'error'; label: string; message: string };

const LAST_MARKET_KEY = 'nightbid:last-market';


export function useNightBid() {
  const [wallets, setWallets] = useState<InitialAPI[]>([]);
  const [injected, setInjected] = useState<string[]>([]);
  const [session, setSession] = useState<WalletSession>();
  const [market, setMarket] = useState<NightBidMarket>();
  const [marketState, setMarketState] = useState<PublicMarketState>();
  const [tx, setTx] = useState<TxStatus>({ kind: 'idle' });
  const [bidsVersion, setBidsVersion] = useState(0);
  const [funds, setFunds] = useState<WalletFunds>();

  // Keep the fee balance fresh so users know when faucet funds / DUST arrive.
  useEffect(() => {
    if (!session) return;
    let cancelled = false;
    const refresh = async () => {
      try {
        const [{ unshieldedAddress }, dust, unshielded] = await Promise.all([
          session.api.getUnshieldedAddress(),
          session.api.getDustBalance(),
          session.api.getUnshieldedBalances(),
        ]);
        const night = Object.values(unshielded).reduce((sum, v) => sum + v, 0n);
        if (!cancelled) setFunds({ unshieldedAddress, dust: dust.balance, night });
      } catch (error) {
        console.warn('[NightBid] could not read wallet balances', error);
      }
    };
    void refresh();
    const timer = setInterval(refresh, 15_000);
    return () => {
      cancelled = true;
      clearInterval(timer);
    };
  }, [session]);

  // Wallet extensions inject asynchronously (and can be enabled while the
  // page is open), so keep checking until a compatible wallet appears.
  useEffect(() => {
    let logged = false;
    const check = () => {
      const found = detectWallets();
      const description = describeInjectedWallets();
      setWallets(found);
      setInjected(description);
      if (!logged && description.length > 0) {
        console.info('[NightBid] window.midnight:', description);
        logged = true;
      }
      return found.length > 0;
    };
    if (check()) return;
    const timer = setInterval(() => check() && clearInterval(timer), 1000);
    return () => clearInterval(timer);
  }, []);

  useEffect(() => {
    if (!market) return;
    const sub = market.state$().subscribe({
      next: setMarketState,
      error: (e) => setTx({ kind: 'error', label: 'Live updates', message: friendlyError(e) }),
    });
    return () => sub.unsubscribe();
  }, [market]);

  const run = useCallback(
    async (label: string, action: () => Promise<string | void>) => {
      setTx({ kind: 'pending', label });
      try {
        const txId = await action();
        setTx(txId ? { kind: 'success', label, txId } : { kind: 'idle' });
        setBidsVersion((v) => v + 1);
      } catch (error) {
        console.error(error);
        setTx({ kind: 'error', label, message: friendlyError(error) });
      }
    },
    [],
  );

  // Only block when we positively know there's no DUST; if balances can't be
  // read, let the wallet decide.
  const noFees = funds !== undefined && funds.dust === 0n;

  /** Runs an action that submits a transaction (and so needs DUST for fees). */
  const runTx = useCallback(
    (label: string, action: () => Promise<string | void>) => {
      if (noFees) {
        setTx({
          kind: 'error',
          label,
          message:
            'Your Midnight wallet has no DUST to pay fees yet. Wait for Lace to finish syncing, get tNIGHT from the faucet and enable DUST generation.',
        });
        return Promise.resolve();
      }
      return run(label, action);
    },
    [noFees, run],
  );

  const connect = useCallback(
    (wallet: InitialAPI) =>
      run('Connecting wallet', async () => {
        const s = await connectWallet(wallet);
        setSession(s);
        const remembered = DEFAULT_CONTRACT_ADDRESS ?? localStorage.getItem(LAST_MARKET_KEY);
        if (remembered) {
          const m = await NightBidMarket.join(s.providers, s.shieldedAddress, remembered);
          setMarket(m);
        }
      }),
    [run],
  );

  const openMarket = (m: NightBidMarket) => {
    localStorage.setItem(LAST_MARKET_KEY, m.contractAddress);
    setMarketState(undefined);
    setMarket(m);
  };

  const deployMarket = () =>
    runTx('Deploying NightBid market', async () => {
      if (!session) return;
      const m = await NightBidMarket.deploy(session.providers, session.shieldedAddress);
      openMarket(m);
      return m.contractAddress;
    });

  const joinMarket = (address: string) =>
    run('Joining market', async () => {
      if (!session) return;
      openMarket(await NightBidMarket.join(session.providers, session.shieldedAddress, address.trim()));
    });

  const leaveMarket = () => {
    localStorage.removeItem(LAST_MARKET_KEY);
    setMarket(undefined);
    setMarketState(undefined);
  };

  return {
    wallets,
    injected,
    funds,
    session,
    market,
    marketState,
    mySealedBids: market ? market.mySealedBids() : [],
    bidsVersion,
    tx,
    dismissTx: () => setTx({ kind: 'idle' }),
    connect,
    deployMarket,
    joinMarket,
    leaveMarket,
    noFees,
    run: runTx,
  };
}
